def rec3(W,V,T):
	n = (W*1000)/70                                                             #Calculating the moles of chlorine produced, by converting mass from kg to grams and using density of chlorine 70 g mol-1
	F = n*2                                                                     #Calculating Faradays of charge
	s = 'The Faradays of charge is ' + round(F,2) + 'F'  
	Q = 96500*F                                                                 #Calculating charge in coulombs
	s = s+ '\nThe Total charge in the cell is ' + round(Q,2) + 'C'
	T = 3600*24                                                                 #Converting time (Duration of electrolysis) from hours to seconds
	s = s + '\nThe Time for which the charge travels is ' + round(T,2) + 'seconds'
	I = Q/T                                                                     #Calculating current in amperes
	s = s + '\nThe Total current in the cell is ' + round(I,2) + 'Amperes'
	P = V*I                                                                     #Calculating the total power generated by the cell in joules
	s = s + '\nThe Total power generated by the cell is ' +round(P,2) + 'Watt'
	return s